-- Generated by `supabase db pull` on 2026-09-03 to capture storage-policy
-- drift: the photos bucket policies were recreated from the dashboard in
-- production, replacing the two hand-written ones. This file originally also
-- dropped the judges table (production simply had not received
-- 20260903000000_judges.sql yet); that part was removed so the table is
-- created everywhere rather than destroyed.

DROP POLICY IF EXISTS "Public read photos" ON "storage"."objects";

DROP POLICY IF EXISTS "Service role full access photos" ON "storage"."objects";

CREATE POLICY "Storage Policy Service Role Access 1io9m69_0" ON "storage"."objects"
  FOR SELECT
  TO "service_role"
  USING ((bucket_id = 'photos'::text));

CREATE POLICY "Storage Policy Service Role Access 1io9m69_1" ON "storage"."objects"
  FOR INSERT
  TO "service_role"
  WITH CHECK ((bucket_id = 'photos'::text));

CREATE POLICY "Storage Policy Service Role Access 1io9m69_2" ON "storage"."objects"
  FOR DELETE
  TO "service_role"
  USING ((bucket_id = 'photos'::text));

CREATE POLICY "Storage Policy Service Role Access 1io9m69_3" ON "storage"."objects"
  FOR UPDATE
  TO "service_role"
  USING ((bucket_id = 'photos'::text));
